# -*- coding: utf-8 -*-
"""Predictive_Sales_Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TBsjOvX3l1t3Y5yjBoyjw_2ezlbPb3X

1. Project Title
**Predictive Sales Forecasting Using Historical Data**


2. Abstract

Predictive Sales Forecasting Using Historical Data is a machine learning-based project designed to analyze previous sales data and predict future sales trends. The system uses historical sales records, performs data cleaning and preprocessing, and identifies monthly sales patterns.

Time-based features such as year, month, quarter, previous-month sales, previous 3-month sales, previous 12-month sales, and rolling averages are created to improve prediction. A Random Forest Regression model is trained using historical data.

The model is evaluated using Mean Absolute Error (MAE), Root Mean Squared Error (RMSE), and R² Score. Finally, the trained model is used to forecast sales for the upcoming six months. Visualizations are generated to compare actual and predicted sales and display future sales trends.


3. Objectives

The main objectives are:

To analyze historical sales data.
To clean and preprocess the dataset.
To identify monthly sales trends.
To create useful time-based features.
To build a machine learning regression model.
To evaluate the prediction performance.
To forecast future sales.
To visualize historical and predicted sales trends.
4. Technologies Used
Technology	Purpose
Python	Main programming language
Pandas	Data manipulation
NumPy	Numerical operations
Matplotlib	Data visualization
Scikit-learn	Machine learning
Random Forest Regressor	Sales prediction
Google Colab / Jupyter Notebook	Development environment


5. Dataset

The project uses a Superstore sales dataset containing historical sales transactions.

The dataset contains:

9,800 rows
18 columns
Order information
Customer information
Product information
Location information
Sales information

Important columns include:

Order ID
Order Date
Ship Date
Customer ID
Segment
Country
City
State
Region
Category
Sub-Category
Product Name
Sales


6. Data Cleaning

The following preprocessing operations were performed:

Checked missing values.
Checked duplicate records.
Removed duplicate rows.
Converted Order Date into date format.
Converted Ship Date into date format.
Checked invalid dates.
Verified the Sales column.
Confirmed the final dataset size.
Cleaning Result
Rows: 9800
Columns: 18
Duplicate Rows: 0
Invalid Order Dates: 0
Invalid Ship Dates: 0

There were only a small number of missing values in the Postal Code column.


7. Exploratory Data Analysis

The transaction-level sales data was grouped by month to calculate total monthly sales.

A line graph was created to identify:

Sales trends
Increasing/decreasing periods
Seasonal patterns
Changes in monthly sales


8. Feature Engineering

The following features were created:

Year
Month_Number
Quarter
Sales_Lag_1
Sales_Lag_3
Sales_Lag_12
Rolling_Average_3
Meaning

Sales_Lag_1
Previous month's sales.

Sales_Lag_3
Sales from three months earlier.

Sales_Lag_12
Sales from twelve months earlier.

Rolling_Average_3
Average sales of the previous three months.

These features provide the machine-learning model with historical information that can help estimate future sales.


9. Machine Learning Model

The project uses:

Random Forest Regression

Random Forest is an ensemble machine learning algorithm that combines multiple decision trees to produce a prediction.

The model was configured with:

RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

The data was divided chronologically into:

80% → Training Data
20% → Testing Data

A chronological split was used because this is a forecasting problem, so future information should not be used to train predictions for earlier periods.


10. Model Evaluation

The model was evaluated using three metrics.

MAE — Mean Absolute Error

Measures the average absolute difference between actual and predicted sales.

RMSE — Root Mean Squared Error

Measures prediction error while giving greater weight to larger errors.

R² Score

Indicates how much of the variation in the target is explained by the model.

Add your actual results here:

MAE       : $________
RMSE      : $________
R² Score  : ________

Important: Use the exact values from your Step 7 output rather than estimating them.


11. Future Sales Prediction

The trained Random Forest model was used to forecast the next six months.

The system generates:

Month
Predicted Sales

Your final table is:

future_results

You can display it using:

future_results


12. Visualizations

The project contains these important graphs:

Graph 1

Historical Monthly Sales Trend

Shows the sales pattern over the historical period.

Graph 2

Actual vs Predicted Sales

Compares actual sales with the model's predictions.

Graph 3

Historical Sales and Future Sales Forecast

Shows historical sales followed by the estimated future sales.

Graph 4

Prediction Error

Shows the difference between actual and predicted sales.


13. Project Workflow

You can put this in your report:

Historical Dataset
       ↓
Data Cleaning
       ↓
Exploratory Data Analysis
       ↓
Monthly Sales Aggregation
       ↓
Feature Engineering
       ↓
Train-Test Split
       ↓
Random Forest Regression
       ↓
Model Evaluation
       ↓
Future Sales Prediction
       ↓
Visualization
       ↓
Final Forecast


14. Conclusion

The Predictive Sales Forecasting project demonstrates how historical sales data can be processed and used for machine learning-based forecasting. The project performs data cleaning, exploratory analysis, feature engineering, model training, evaluation, and future prediction.

The Random Forest Regression model provides estimated future sales based on historical patterns and engineered time-based features. The visualizations make the sales trends and model predictions easier to understand.

This project demonstrates the practical use of Python, data preprocessing, machine learning, regression, and data visualization for predictive analytics.
"""

import zipfile
import os

with zipfile.ZipFile("archive.zip", "r") as zip_ref:
    zip_ref.extractall("data")

print("Dataset extracted successfully!")
print(os.listdir("data"))

"""
 Load and Inspect the Dataset"""

import pandas as pd

# Load the dataset
df = pd.read_csv("data/train.csv")

# Display the first 5 rows
df.head()

# Check the number of rows and columns
print("Dataset Shape:", df.shape)

# Display column names
print("\nColumn Names:")
print(df.columns.tolist())

# Display basic information
print("\nDataset Information:")
df.info()

"""Data Cleaning

"""

# STEP 3 - DATA CLEANING

# Make a copy of the original dataset
clean_df = df.copy()

# 1. Check for missing values
print("Missing values before cleaning:")
print(clean_df.isnull().sum())

# 2. Check for duplicate rows
print("\nNumber of duplicate rows:")
print(clean_df.duplicated().sum())

# 3. Remove duplicate rows
clean_df = clean_df.drop_duplicates()

# 4. Convert Order Date to date format
clean_df["Order Date"] = pd.to_datetime(
    clean_df["Order Date"],
    dayfirst=True,
    errors="coerce"
)

# 5. Convert Ship Date to date format
clean_df["Ship Date"] = pd.to_datetime(
    clean_df["Ship Date"],
    dayfirst=True,
    errors="coerce"
)

# 6. Check for invalid dates
print("\nInvalid Order Dates:", clean_df["Order Date"].isna().sum())
print("Invalid Ship Dates:", clean_df["Ship Date"].isna().sum())

# 7. Check Sales column
print("\nSales data type:", clean_df["Sales"].dtype)

# 8. Final dataset information
print("\nDataset after cleaning:")
print("Rows:", clean_df.shape[0])
print("Columns:", clean_df.shape[1])

clean_df.head()

"""
Exploratory Data Analysis (EDA)"""

# STEP 4 - EXPLORATORY DATA ANALYSIS

# Create a copy for analysis
sales_df = clean_df.copy()

# Create a Month column
sales_df["Month"] = sales_df["Order Date"].dt.to_period("M")

# Calculate total sales for each month
monthly_sales = (
    sales_df.groupby("Month")["Sales"]
    .sum()
    .reset_index()
)

# Convert Month back to datetime
monthly_sales["Month"] = monthly_sales["Month"].dt.to_timestamp()

# Display the monthly sales
monthly_sales.head(10)

"""Check the monthly dataset"""

print("Number of months:", len(monthly_sales))

print("\nMonthly Sales Statistics:")
print(monthly_sales["Sales"].describe())

"""Create the first graph 📈"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14, 6))

plt.plot(
    monthly_sales["Month"],
    monthly_sales["Sales"],
    marker="o"
)

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.grid(True)

plt.tight_layout()
plt.show()

"""Feature Engineering"""

# STEP 5 - FEATURE ENGINEERING

# Make a copy
model_df = monthly_sales.copy()

# Create time-based features
model_df["Year"] = model_df["Month"].dt.year
model_df["Month_Number"] = model_df["Month"].dt.month
model_df["Quarter"] = model_df["Month"].dt.quarter

# Display the result
model_df.head()

"""Create previous-sales features"""

# Create lag features

model_df["Sales_Lag_1"] = model_df["Sales"].shift(1)
model_df["Sales_Lag_3"] = model_df["Sales"].shift(3)
model_df["Sales_Lag_12"] = model_df["Sales"].shift(12)

# Display the data
model_df.head(15)

"""Create rolling average"""

# Create a 3-month rolling average

model_df["Rolling_Average_3"] = (
    model_df["Sales"]
    .shift(1)
    .rolling(window=3)
    .mean()
)

model_df.head(15)

"""Remove rows with missing feature values"""

# Remove rows with missing values created by lag features

model_df = model_df.dropna().reset_index(drop=True)

print("Dataset after feature engineering:")
print("Rows:", model_df.shape[0])
print("Columns:", model_df.shape[1])

model_df.head()

"""Select the features and target"""

# Select input features
features = [
    "Year",
    "Month_Number",
    "Quarter",
    "Sales_Lag_1",
    "Sales_Lag_3",
    "Sales_Lag_12",
    "Rolling_Average_3"
]

X = model_df[features]
y = model_df["Sales"]

print("Features (X):")
print(X.head())

print("\nTarget (y):")
print(y.head())

"""Split the data correctly"""

# Split data chronologically

split_index = int(len(model_df) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

"""Train the Prediction Model 🤖"""

# STEP 6 - MACHINE LEARNING MODEL

from sklearn.ensemble import RandomForestRegressor

# Create the model
model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

print("Model created successfully!")

"""Train the model"""

# Train the model using training data

model.fit(X_train, y_train)

print("Model training completed successfully!")

"""Make predictions"""

# Make predictions on the test data

y_pred = model.predict(X_test)

print("Predictions generated successfully!")

# Display the first 10 predictions
for actual, predicted in zip(y_test.head(10), y_pred[:10]):
    print(f"Actual: ${actual:,.2f} | Predicted: ${predicted:,.2f}")

"""Compare Actual vs Predicted"""

# Create a comparison table

results = pd.DataFrame({
    "Month": model_df.loc[X_test.index, "Month"],
    "Actual Sales": y_test.values,
    "Predicted Sales": y_pred
})

results.head(10)

"""Visualize Actual vs Predicted 📈"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14, 6))

plt.plot(
    results["Month"],
    results["Actual Sales"],
    marker="o",
    label="Actual Sales"
)

plt.plot(
    results["Month"],
    results["Predicted Sales"],
    marker="o",
    label="Predicted Sales"
)

plt.title("Actual vs Predicted Sales")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.legend()
plt.xticks(rotation=45)
plt.grid(True)

plt.tight_layout()
plt.show()

"""Evaluate the Model 📊"""

# STEP 7 - MODEL EVALUATION

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Calculate evaluation metrics
mae = mean_absolute_error(y_test, y_pred)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

r2 = r2_score(y_test, y_pred)

# Display results
print("Model Evaluation Results")
print("-" * 30)
print(f"MAE  : ${mae:,.2f}")
print(f"RMSE : ${rmse:,.2f}")
print(f"R² Score : {r2:.4f}")

"""Create an Actual vs Predicted Error"""

# Calculate prediction error

results["Error"] = results["Actual Sales"] - results["Predicted Sales"]

results["Absolute Error"] = abs(results["Error"])

results.head(10)

"""plat the prediction errors"""

plt.figure(figsize=(14, 6))

plt.bar(
    results["Month"],
    results["Error"]
)

plt.axhline(
    y=0,
    linestyle="--"
)

plt.title("Prediction Error")
plt.xlabel("Month")
plt.ylabel("Error (Actual - Predicted)")
plt.xticks(rotation=45)
plt.grid(axis="y")

plt.tight_layout()
plt.show()

"""Future Sales Prediction 🔮"""

# STEP 8 - FUTURE SALES PREDICTION

# Get the last month in our dataset
last_month = model_df["Month"].max()

# Create the next 6 months
future_dates = pd.date_range(
    start=last_month + pd.DateOffset(months=1),
    periods=6,
    freq="MS"
)

future_df = pd.DataFrame({
    "Month": future_dates
})

future_df

"""Prepare future features"""

# Create future prediction features

history = model_df[["Month", "Sales"]].copy()

future_predictions = []

for date in future_dates:

    # Previous month sales
    lag_1 = history.iloc[-1]["Sales"]

    # Sales from 3 months ago
    lag_3 = history.iloc[-3]["Sales"]

    # Sales from 12 months ago
    lag_12 = history.iloc[-12]["Sales"]

    # Average of previous 3 months
    rolling_avg = history["Sales"].tail(3).mean()

    # Create feature row
    features_future = pd.DataFrame({
        "Year": [date.year],
        "Month_Number": [date.month],
        "Quarter": [date.quarter],
        "Sales_Lag_1": [lag_1],
        "Sales_Lag_3": [lag_3],
        "Sales_Lag_12": [lag_12],
        "Rolling_Average_3": [rolling_avg]
    })

    # Predict sales
    prediction = model.predict(features_future)[0]

    # Store prediction
    future_predictions.append(prediction)

    # Add prediction to history
    history = pd.concat([
        history,
        pd.DataFrame({
            "Month": [date],
            "Sales": [prediction]
        })
    ], ignore_index=True)

"""Visualize Future Sales 📈"""

# STEP 9 - HISTORICAL + FUTURE SALES FORECAST

import pandas as pd
import matplotlib.pyplot as plt

# Create future results DataFrame
future_results = pd.DataFrame({
    "Month": future_df["Month"],
    "Predicted Sales": future_predictions
})

# Display forecast table
print("Future Sales Forecast:")
display(future_results)

# Create graph
plt.figure(figsize=(14, 6))

# Historical sales
plt.plot(
    model_df["Month"],
    model_df["Sales"],
    marker="o",
    label="Historical Sales"
)

# Future predictions
plt.plot(
    future_results["Month"],
    future_results["Predicted Sales"],
    marker="o",
    linestyle="--",
    label="Forecasted Sales"
)

plt.title("Historical Sales and Future Sales Forecast")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.legend()
plt.xticks(rotation=45)
plt.grid(True)

plt.tight_layout()
plt.show()

"""Historical Sales Trend"""

# STEP 9.1 - HISTORICAL SALES TREND

plt.figure(figsize=(14, 6))

plt.plot(
    model_df["Month"],
    model_df["Sales"],
    marker="o"
)

plt.title("Historical Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.xticks(rotation=45)
plt.grid(True)

plt.tight_layout()
plt.show()

"""Actual vs Predicted Sales"""

# STEP 9.2 - ACTUAL VS PREDICTED SALES

plt.figure(figsize=(14, 6))

plt.plot(
    results["Month"],
    results["Actual Sales"],
    marker="o",
    label="Actual Sales"
)

plt.plot(
    results["Month"],
    results["Predicted Sales"],
    marker="o",
    linestyle="--",
    label="Predicted Sales"
)

plt.title("Actual vs Predicted Sales")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.legend()
plt.xticks(rotation=45)
plt.grid(True)

plt.tight_layout()
plt.show()

"""Future Sales Forecast"""

# Create the future results table

future_results = pd.DataFrame({
    "Month": future_dates,
    "Predicted Sales": future_predictions
})

future_results

"""Model Performance Summary"""

# STEP 9.4 - MODEL PERFORMANCE SUMMARY

print("====================================")
print("   PREDICTIVE SALES FORECASTING")
print("====================================")

print(f"MAE       : ${mae:,.2f}")
print(f"RMSE      : ${rmse:,.2f}")
print(f"R² Score  : {r2:.4f}")

print("\nFuture Sales Forecast:")
print('future_results')

"""Save the Forecast"""

# STEP 8 - CREATE FUTURE RESULTS

future_results = pd.DataFrame({
    "Month": future_dates,
    "Predicted Sales": future_predictions
})

future_results